<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Mono.Addins" Version="1.4.2-alpha.4" />
		<ProjectReference Include="..\Pinta\Pinta.Core\Pinta.Core.csproj" />
		<EmbeddedResource Include=".addin.xml" />
	</ItemGroup>
</Project>